config/routes.rb
Rails.application.routes.draw do
  # resources :users
  resources :posts
  devise_for :users, controllers: { # <- rails g devise:controllers sagt so machen
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_for :admins
  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # validates :username, format: { with: /\A[A-Z0-9]+\z/i }, uniqueness: { case_sensitive: false }

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @posts = Post.find_each
    # @posts.order(:created_at)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
    @post = Post.find(params[:id])
  end


  def create
    post = Post.new(post_params.merge(user: current_user))

    if post.save
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :title)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if User.find(params[:id])
      @user = User.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="text-center">
  <%  if user_signed_in? %>

    <h1 class="m-2">members feed</h1>

    <%= Post.find_each do |post| %> 
      <div class="card card-small mx-auto m-4" style="width: 25rem;">
        <img src=<%= "https://picsum.photos/300/200?random=#{post.id}" %> class="card-img-top">
        <div class="card-body">
          <h5 class="card-title"><%= link_to post.title, post %></h5>
          <p class="card-text">by <%= post.user.username %> <%= time_ago_in_words(post.created_at) %> ago</p>
        </div>
      </div>
    <% end %>

    <div class="mt-3">
      <%= link_to "Create Post", new_post_path, class: "btn btn-primary" %>
    </div>

  <%  else %>
    <h1>Feed for Members Only</h1>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "Log In", new_user_session_path, class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Members Only</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-item"> <%= link_to "All Posts", root_path, class: "nav-link" %> </a>
          <%# <li class="nav-item"> <%= link_to "All Users", users_path, class: "nav-link" %> 
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <%# <li class="nav-item"> <%= link_to "Account", user_path, class: "nav-link" %> </li> 
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<div style="max-width: 300px" >

  <%= form_with model: Post.new, url: posts_path, local: true, method: :post do |f| %>
        <div class="mb-3">
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
  
        <div class="mb-3">
          <%= f.label :body, class: "form-label" %>
          <%= f.text_field :body, class: "form-control" %>
        </div>
  
        <div class="mb-3"><%= f.submit %></div>
  
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Prost</h1>
<%= @post.title %>
<%= @post.body %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user %>
      joined <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="container border my10">
  <h1> <%= @user.username %> </h1>
  <ul>
    <li> <%= @user.email %> </li>
    <li> <%= @user.created_at %> </li>
  </ul>
  <div>
    <div><%= button_to "Edit Account", edit_user_registration_path, method: :get, class: "btn btn-primary" %> </div>
  </div>
</div>